### ISSUE TITLE
reduce font-size in #b_1_3 and #b_1_4 ?

### ISSUE THREAD

**Issue by gregsadetsky** [yehwansong/sfpc_2019spring_archive#2]
At certain widths, some of the artist names are not visible. See attached example -- Luisa and Mar's name are not there.

Reducing the font-size seems to work -- maybe there's another solution?

![Screen Shot 2019-07-15 at 7 52 10 PM](https://user-images.githubusercontent.com/1017304/61256298-4808f880-a73a-11e9-85b6-d75e7cdbd85f.png)

**Comment by yehwansong** [comment]
I Just made it to have 2 lines if the ratio is less than 1270/947:)

**Comment by gregsadetsky** [comment]
yay! closing
